In [1]:
import torch # 导入torch模块

## 1. 张量
**张量(tensor)**表示由一个数值组成的数组，这个数组可能有多个维度。张量中的每个值都称为张量的元素(element)。
* **向量(vector)**：具有一个轴的张量
* **矩阵(matrix)**：具有两个轴的张量
* **张量的存储位置**：如果没有额外指定，否则新的张量将存储在内存中，并采用基于CPU的计算


使用arange创建一个行向量x，这个行向量包含从0开始的前12个整数,它们被默认创建为**浮点数**。

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

通过张量的 shape 属性来访问张量的形状（沿每个轴的长度）

In [3]:
x.shape

torch.Size([12])

张量中元素的总数，即形状的所有元素乘积，可以检查它的大小（size）

In [4]:
x.numel()

12

改变一个张量的形状而不改变元素数量和元素值，可以调用 **reshape**函数。

注意，通过改变张量的形状，张量的大小不会改变

In [5]:
X = x.reshape(3, 4)
X1 = x.reshape(-1, 4) # 张量自动推断的维度放置 -1 来调用
X, X1

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

使用全0、全1、其他常量或者从特定分布中随机采样的数字来初始化矩阵

In [6]:
# 创建一个形状为（2,3,4）的张量，其中所有元素都设置为0
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
# 创建一个形状为（2， 3， 4）的张量，其中所有元素都设置为1
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

## 2. 数据操作
### 2. 1 赋值
 * 从某个特定的概率分布中随机采样来得到张量中每个元素的值。

创建一个形状为（3， 4）的张量，其中每个元素都服从均值为0、标准差为1的标准高斯（正态）分布中随机采样

In [8]:
torch.randn(3, 4)

tensor([[ 0.7314,  3.3725, -0.2040,  1.1353],
        [ 0.0404,  0.0576, -1.1510,  0.7484],
        [ 0.0246, -0.0779,  0.5574, -0.8140]])

* 通过提供包含数值的 Python 列表（或嵌套列表）来为所需张量中的每个元素赋予确定值。

In [22]:
ten = torch.tensor(([2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]))
ten

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

**轴0（行）**： 形状的第一个元素

**轴1（列）**： 形状的第二个元素

In [39]:
print(ten.shape) # 打印形状
# 所有元素加起来
ten.sum() 

torch.Size([3, 4])


tensor(30)

In [36]:
# 每列中的所有行求和，行数（轴0）为1
ten.sum(dim=0, keepdim = True) # 保留行size([1, 4])

tensor([[7, 6, 9, 8]])

In [42]:
# 每行中的所有列求和，列数（轴1）为1
ten.sum(dim=1, keepdim = True) # 保留列 size([3, 1])

tensor([[10],
        [10],
        [10]])

### 2.2 运算
按元素运算：
* 常见的标准算术运算符（+、-、\*、/和 \**）

In [32]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2.0, 2, 2, 2])
x + y, x - y, x / y, x * y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([ 1.,  4., 16., 64.]))

* 求幂

In [33]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

线性代数运算：
 * 向量点积
 * 矩阵乘法

 * 张量连接（升维）

In [44]:
X = torch.arange(12, dtype = torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X,Y), dim = 0), torch.cat((X,Y), dim = 1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

逻辑运算：
* ==、>=、<=、>、<

In [46]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

## 3. 广播机制
当进行按元素操作时，如果运算的张量形状不同，可以通过 Pytorch 中的**广播机制**来执行该操作。

其工作方式：
* 首先，通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状
* 其次，对生成的数组执行按元素操作

In [48]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b, a + b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

## 4. 索引和切片
张量中的元素访问两种方式：
* 与Python数组一样，可以通过**索引**访问，索引号从0开始访问第一个元素
* 与标准Python列表一样，可以通过**负索引**根据元素到列表尾部的相对位置访问元素

In [50]:
X[-1], X[1:3]  # [-1] 选择最后一个元素， [1:3]选择第二个和第三个元素

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [52]:
X[1, 2] = 9 # 通过指定索引来将元素写入矩阵
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [54]:
X[0:2, :] = 12 # 多个元素赋值相同的值
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 5. 节省内存
运行一些操作可能会导致为新结果分配内存，如**Y = Y + X**，将取消引用Y指向的张量，而是指向新分配的内存处的张量

In [56]:
before = id(Y) # id()函数提供内存中引用对象的确切地址
Y = Y + X
id(Y) == before

False

可以使用**切片表示法**将操作的结果分配到先前分配的数组，避免新开内存

In [59]:
Ｚ = torch.zeros_like(Y) # 形状、元素类型均与Ｙ相同，并且Ｚ中的所有元素为０
Z, Y

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[14., 13., 16., 15.],
         [13., 14., 15., 16.],
         [12., 12., 12., 12.]]))

In [61]:
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 140326888866880
id(Z): 140326888866880


也可以使用　X[:] = X + Y 或　X += Y 来减少操作的内存开销

In [62]:
before = id(X)
X += Y
id(X) == before

True